### PR TITLE
Update dependencies + Issue new version

### PR DESCRIPTION
**Pull request by dCSeven**
* Update the dependencies (kept on the safe side, i think that even more would be possible w/o code changes)
* Improve versioning so that it is possible to use this gem with bundler from this repo, without getting errors (about VERSION file not found)
* Fix conversation_id checking in SCRAM-SHA-1 (shouldn't have any great security impact)

### CODE REVIEW

**Comment by jsaak** [comment]
Do you want to be admin in this repo? I have little interest doing so, bcg long left.

**Comment by dCSeven** [comment]
Before it dies I'll do it,
but I would need to have access to rubygems too, to be able to release sthg.

**Comment by bcg** [comment]
I'm happy to push a new gem if you are willing to stand behind the changes here (and merge). I'm not in a position to test and validate things. I'm also happy to give someone else rubygems access to manage updates moving forward.

**Comment by dCSeven** [comment]
Sure

**Comment by bcg** [comment]
@dCSeven sent you an invite to be a collaborator

**Pull request merged**
